name: atlantic_web3_contract
version: 0.0.1

environment:
  sdk: ^3.6.0
  flutter: '>=3.10.0'

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  #atlantic web3
  atlantic_web3:
    path: ../atlantic_web3
  #providers
  web3_providers_http:
    path: ../web3_providers_http
  web3_providers_ipc:
    path: ../web3_providers_ipc
  web3_providers_ws:
    path: ../web3_providers_ws

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
